FROM python:3.10-slim

WORKDIR /app

# copy dependencies and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy project files
COPY src/ ./src/
COPY models/ ./models/
COPY data/processed/ ./data/processed/

EXPOSE 8501

CMD ["streamlit", "run", "src/app_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
